### ISSUE TITLE
do not report missing io.k8s.description if description is present

### ISSUE THREAD

**Issue by fkluknav** [user-cont/colin#129]
Do not report missing 'io.k8s.description' if 'description' is present. If one exists, the build system copies it to the other. The same applies for the other way, missing description and present io.k8s.description. No need to have both in Dockerfiles.

**Comment by lachmanfrantisek** [comment]
Yes, the image/container needs both, but in the dockerfile one of them is enough.

Thanks for mentioning that.

-----

This will need:
- use current checks only for `container`/`image`
- create a new dockerfile-only check
