### ISSUE TITLE
Pluggable output generation

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#14]
* configurable via CLI
* enable user to select output format (doesn't mean you should implement all of them)
  * machine readable (e.g. json)
  * human readable
    * short (provide design first, this needs brainstorming)
    * verbose (provide design first, this needs brainstorming)

**Comment by lachmanfrantisek** [comment]
Let's discuss some example:

config:
```json
{
  "group1": {
    "required": [
      "check1",
      "check2"
    ],
    "optional": [
      "check3",
      "check4"
    ]
  },
  "group2": {
    "required": [
      "check5",
      "check6"
    ],
    "optional": [
      "check7",
      "check8"
    ]
  }
}
```

# JSON

- Copy the config structure and add the properties of check result object.
- `--json` / `-j` option.
- Print to stdout or save to file?

```json
{
  "group1": {
    "required": [
      {
        "name": "check1",
        "ok": true,
        "status": "passed",
        "message": "Message of the check1.",
        "description": "Description of the check1.",
        "reference_url": "http://reference.url"
      },
      {
        "name": "check2",
        "ok": false,
        "status": "failed",
        "message": "Message of the check2.",
        "description": "Description of the check2.",
        "reference_url": "http://reference.url"
      }
    ],
    "optional": [
      {
        "name": "check3",
        "ok": true,
        "status": "passed",
        "message": "Message of the check3.",
        "description": "Description of the check3.",
        "reference_url": "http://reference.url"
      },
      {
        "name": "check4",
        "ok": false,
        "status": "warning",
        "message": "Message of the check4.",
        "description": "Description of the check4.",
        "reference_url": "http://reference.url"
      }
    ]
  },
  "group2": {
  }
}
```

# Human

## Normal
- grouped
- check names
- result ('ok' x 'nok'), status ('failed', 'warn', 'passed', ...)
- coloured

## Short
- Only some statistic (or print statistics with `--stat` option?)

## Verbose (`-v`)
- like normal + message

## Verbose verbose (`-vv`)
- like verbose + description + reference url

**Comment by TomasTomecek** [comment]
* json proposal: lgtm
  * print to stdout
  * I actually propose: --output=json

I think that analyzer output and logging verbosity are two different things: let's provide multiple predefined output types, such as ones you wrote: short, normal, detailed, json. -v  and -vv should then control log level, which is something different.

**Comment by lachmanfrantisek** [comment]
> I think that analyzer output and logging verbosity are two different things: let's provide multiple predefined output types, such as ones you wrote: short, normal, detailed, json. -v and -vv should then control log level, which is something different.

Ok, I get it.

**Comment by lachmanfrantisek** [comment]
I've updated the previous comment with the format example. WDYT?

**Comment by TomasTomecek** [comment]
I like detailed, I like short but normal makes me a bit fuzzy; how about doing a brainstorming session? Wed/Thu

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  yes, +1 for the Wed

**Comment by lachmanfrantisek** [comment]
I've updated the previous comment to show our idea.
