### ISSUE TITLE
drop checks for io.openshift.expose-services

### ISSUE THREAD

**Issue by ktdreyer** [user-cont/colin#165]
Note that OpenShift has removed references to this `io.openshift.expose-services` label: https://github.com/openshift/openshift-docs/pull/10531

[RHBZ 1583274](https://bugzilla.redhat.com/1583274) says "This is not consumed in any meaningful way by OpenShift."

If OpenShift is removing this, we should not refer to it in colin, or users may add this old/unused label to their Dockerfiles simply to silence the linter warning.

**Comment by TomasTomecek** [comment]
Ken, good point, fix incoming.

The reason we had this check in colin is this doc:
https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

Gonna fix it there as well.

**Comment by TomasTomecek** [comment]
Citing @bparees from an internal conversation:
> So I would say the io.openshift.* labels are *not* relevant.

Hence I removed both of them.

**Comment by ktdreyer** [comment]
Thanks @TomasTomecek !

Would you please release a new version with this change?

**Comment by TomasTomecek** [comment]
@ktdreyer sorry for late response, those conferences...

Is this for sake of internal checking (because we have a dedicated internal config for that) or are you using upstream colin in your infrastructure?

**Comment by ktdreyer** [comment]
No problem!

That's right, I want to be sure this change makes it through to RH's internal configuration.

**Comment by TomasTomecek** [comment]
@dhodovsk are we running colin internally w/o checking for these labels?
