### ISSUE TITLE
#151 doesn't perform well

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#172]
Once we merge #151, we should work on optimization right away. Internally we use 2 rulesets and since an image is being pulled twice per run, it results into 4 pulls per the whole validation run. That's completely unacceptable, we should do only a single pull and transform between formats locally. The thing is that skopeo is not capable to transform between some formats.

**Comment by lslebodn** [comment]
If there is not a simple way how to convert one format to another. Then 1st step can be to reuse already pulled images between two colin runs.

**Comment by lslebodn** [comment]
BTW, I played a little bit with skopeo and I managed to download images as tarball from docker registry and then locally convert tarball to ostree.

I played with that as root with standard location expected by atomic utility. But it should work also for unprivileged user. So we can pull image outside of colin and handle retries (issues with network) there.
And colin would just run checks for already available data.

**Comment by TomasTomecek** [comment]
@lslebodn++ you are absolutely correct! I managed to do this:
```
$ skopeo copy docker://docker.io/library/busybox docker-archive:asdqwe2.tar
Getting image source signatures
Copying blob sha256:8c5a7da1afbc602695fcb2cd6445743cec5ff32053ea589ea9bd8773b7068185
 716.06 KB / 716.06 KB [====================================================] 0s
Copying config sha256:e1ddd7948a1c31709a23cc5b7dfe96e55fc364f90e1cebcde0773a1b5a30dcda
 1.46 KB / 1.46 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

$ ATOMIC_OSTREE_REPO=$PWD/lolzor atomic pull --storage=ostree dockertar:/$PWD/asdqwe2.tar
Getting image source signatures
Copying blob sha256:f9d9e4e6e2f0689cd752390e14ade48b0ec6f2a488a05af5ab2f9ccaf54c299d
 1.31 MB / 1.31 MB [========================================================] 0s
Copying config sha256:e1ddd7948a1c31709a23cc5b7dfe96e55fc364f90e1cebcde0773a1b5a30dcda
 1.46 KB / 1.46 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
```

As you suggest, we can pull the image just once as a tarball and then convert it locally to different formats we need. I hope to provide a fix for that either this week or next week.
