### ISSUE TITLE
Make info subcommand

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/colin#183]
Since we are using more tools in Colin, it would be nice to have some `colin info` command to print versions of the used tools (e.g. conu, skopeo, podman, ...)

Like `podman info`.

It can be useful when debugging or receiving new issues.

----

Shown info (feel free to edit):
- versions:
    - colin
    - conu
    - podman
    - skopeo
    - ostree
- path to the colin-cli
- Python version | kernel/system info ??? Useful when getting info from others.

**Comment by lachmanfrantisek** [comment]
First version:
```
$ colin info
colin 0.1.0 /home/flachman/.local/lib/python3.6/site-packages/colin
conu 0.5.0 /home/flachman/.local/lib/python3.6/site-packages/conu
podman version 0.9.3-dev
skopeo version 0.1.31-dev commit: 59a6cc2159f154cb7a271c7fde5457b869bb7414
libostree:  Version: 2018.8  Git: c62a153558ae579f420cdd57afdaec7264394224
```

I will send a pull request...

**Comment by TomasTomecek** [comment]
looks good; it could be also worth doing `rpm -q $package`

**Comment by lachmanfrantisek** [comment]
> looks good; it could be also worth doing rpm -q $package

It does not work for PyPI packages or other ditributions. But for `ostree`, it can be usefull:

```
$ ostree --version
libostree:
 Version: 2018.8
 Git: c62a153558ae579f420cdd57afdaec7264394224
 Features:
  - libcurl
  - no-http2
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - openssl
  - libmount
  - release
  - p2p
```

**Comment by TomasTomecek** [comment]
Yup, looks good.

I would do it like this: check if RPM is installed, if it is, report version, if not, check PyPI package and report if it's installed. Report path to the module all the time.
