### ISSUE TITLE
Running tests on CI worker directly is not ideal.

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#190]
Right now there are at least two instances when the VM was not clean and this caused a test failure.

So this issue is just a reminder that we want to run tests in a container.

**Comment by lslebodn** [comment]
tests are executed from container for a long time
https://github.com/user-cont/colin/blob/2e91e7e76be006d0e7d481ce5b5a634fc0f41deb/Makefile#L15

Please reopen if you meant something different
