### ISSUE TITLE
f28 unable to use colin

### ISSUE THREAD

**Issue by jscotka** [user-cont/colin#198]
seems thant I'm unable to use colin what is in fedora

```
$ sudo rpm -qa colin
colin-0.0.4-3.fc28.noarch

$ sudo colin check fedora
Error: Ruleset directory cannot be found.

$ colin --version
colin, version 0.0.4

$ sudo colin check -f rulesets/fedora.json fedora 
Error: 'str' object has no attribute 'items'
```

**Comment by lachmanfrantisek** [comment]
It seems like a very old version.

**Comment by lachmanfrantisek** [comment]
Version `0.2.0` should appear soon:
https://bodhi.fedoraproject.org/updates/FEDORA-2018-89d470cd1a

The newest one (`0.2.1`) will take some time.

**Comment by lachmanfrantisek** [comment]
@jscotka should be there now:

https://bodhi.fedoraproject.org/updates/FEDORA-2018-89d470cd1a
