### ISSUE TITLE
Python <3.5 compatibility

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/colin#202]
As now, the loader does not work with the older versions of python.

Do we want to:
- drop support -> remove versions from `setup.py`
- or fix that?

**Comment by hugovk** [comment]
Python 3.4 is soon EOL and generally little used, so I think that's good to go.

https://en.wikipedia.org/wiki/CPython#Version_history

And many projects are pledging to drop Python 2.7 on or before its EOL date 2020-01-01.

https://python3statement.org

**Comment by lachmanfrantisek** [comment]
@hugovk yes, we should definitely be compatible with python >=3.5 (Not 100% sure about `3.5` now.). 

We need to make this clear to users and ideally run tests for all supported versions.

Some pros/cons:

:heavy_plus_sign: 
- Colin itself was written in a compatible way (mostly with *six* package). There is only one small part, which does not work.

:heavy_minus_sign: 
- We should udpate the loading function. (There is some work with that.)
- We can have problems with multiple installed versions (e.g. CLI script).
- More test targets.

@TomasTomecek @jscotka WDYT

**Comment by TomasTomecek** [comment]
@hugovk +1

Let's support python versions which are in stable, supported Fedora versions (this is how we run colin). So we should 100% support python 3.6; 3.5 is best effort and that's it. We can actually easily drop support for python2 by the end of the year. I think we never used colin with python2.

**Comment by ericwb** [comment]
I recommend preventing support of Python2 programmatically.  I happened to install Colin in a Linux VM of mine and it throws a cryptic traceback if run using Python2.  A good way to prevent this is put the following in the setup.py:

```
setup(
   ...
   python_requires='>=3.6'
   ...
)
```

**Comment by hugovk** [comment]
@ericwn Good idea, please see PR https://github.com/user-cont/colin/pull/237.

**Comment by TomasTomecek** [comment]
shall we close this then?

**Comment by lslebodn** [comment]
> @ericwn Good idea, please see PR #237.

Closing
