### ISSUE TITLE
[question] match or search for regex?

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/colin#205]
When checking labels, the regular expression can be used.

Is it better to use `pattern.match` or `pattern.search`?

https://docs.python.org/3/howto/regex.html#match-versus-search

```
present = target_labels is not None and not set(labels).isdisjoint(set(target_labels))

    if present:
        if required and not value_regex:
            return True
        elif value_regex:
            pattern = re.compile(value_regex)
            present_labels = set(labels) & set(target_labels)
            for l in present_labels:
                if not bool(pattern.match(target_labels[l])):
                    return False
            return True
        else:
            return False

    else:
        return not required
```

**Comment by jscotka** [comment]
@lachmanfrantisek based what you want.
``re.match("EXPR", TEXT)`` is more less same as ``re.search("^EXPR", TEXT)``
and 
``re.match(".*EXPR", TEXT)`` is more less same as ``re.search("EXPR", TEXT)``
maybe internal implementation of ``re.match`` could be faster because it has to match from begin of TEXT, but from logic of regular expression it is same.

**Comment by jscotka** [comment]
maybe ``re.match`` is better for you, in case you would like to match whole, ``re.seach`` for ``label`` could cause find ``sublabel`` too

**Comment by lachmanfrantisek** [comment]
@jscotka I know we can use both, but I would like to know others opinion... What is more practical for people in this use case.

(I am not sure if we can realize the performance impact, but the reason with sub-labels seems logic.

**Comment by TomasTomecek** [comment]
let's do search since no one really knows what value should be placed in that label
