### ISSUE TITLE
readme: please provide section about usage

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#32]
I have no idea what should I do.

* [x] running colin from git #35
* [x] running colin from a standard installation
* [x] checking containers
* [x] checking images
* [x] selecting config
* [x] update asciinema before release, per @lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
The asciinema is little outdated as well...

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  can we close this?

**Comment by TomasTomecek** [comment]
:+1:
