### ISSUE TITLE
testing: prepare a set of images

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#56]
we should have a dedicated set of images for integration testing of colin

* [x] placed in `tests/`, e.g. `tests/data/`
* [x] defined by dockerfiles
* [x] built as part of integration testing process

**Comment by phracek** [comment]
Nowadays, we have only one Dockerfile https://github.com/user-cont/colin/blob/master/tests/data/Dockerfile

**Comment by TomasTomecek** [comment]
All done then, good job!
