### ISSUE TITLE
Naming of checks

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/colin#6]
Each check has `filename` and `name` property in the implemented class.

There are two questions:

- Which one should be in the config file?
- If the `filename` has to be same as the `name` property?

**Comment by phracek** [comment]
I see the point. I think `filename` and the` name` property` have to be the same. Class itself checks `com.redhat.component`.
I don't think it is a good reason to name filename as `com.redhat.component.py`
May be my wrong understanding, why would you like to expand `filename` into instruction e.g.`com.redhat.component`?

**Comment by lachmanfrantisek** [comment]
OK,

my idea:

`filename` == `name` property != `label` property

e.g.:
file `com_redhat_component_label.py`:
```
name="com_redhat_component_label",
label="com.redhat.component"
```

**Comment by lachmanfrantisek** [comment]
@phracek  @TomasTomecek 

If it is ok, I will correct the checks, that are already here.

**Comment by phracek** [comment]
It make sense to me.

**Comment by lachmanfrantisek** [comment]
@phracek This implies that one file contains exactly one test.

**Comment by TomasTomecek** [comment]
> This implies that one file contains exactly one check.

Seems to be pretty strict. How about this:

    Which one should be in the config file?

Filename would be required, name would be optional and would imply name == filename.

    If the filename has to be same as the name property?

Ideally we would have multiple check classes in a single file.

WDYT?

**Comment by lachmanfrantisek** [comment]
@TomasTomecek 

In your example, what will be in the config file, the filename?

So, we will have:
- group (folder name, can be used for packaging)
- each group can have multiple check files
- each check file can have multiple checks.

**Comment by TomasTomecek** [comment]
Do we actually need those groups? Does it make sense?

It would feel like double namespacing: I think it should be enough to namespace just on files and ditch groups for now. Am really interested in hearing your thoughts.

**Comment by lachmanfrantisek** [comment]
The original idea of groups was to be able to package them separately.

We can do following:

## First
- Structure:
   - Group (folder) - related checks
   - File - one check
   - All classes in the file check the same thing. (independently not important)
- The configuration specifies `folder:filename`.
- Three layers, many small files (most of the checks will probably have one-class) -> more clear than the second approach?
- I've started to implement this, but it is not important. 

## Second
- Structure:
   - Group (file) - related checks
   - Each class in the file implements one check.
- The configuration specifies `file:classname`
- Huge files.

**Comment by TomasTomecek** [comment]
> The original idea of groups was to be able to package them separately.

I would not very about that while we are at the start.

I like the 2nd one since it's simpler. But if you already have 1st one implemented, let's go with it, create an initial prototype and evaluate it.

**Comment by TomasTomecek** [comment]
What's the status here?

**Comment by phracek** [comment]
@jscotka: This is your issue

**Comment by TomasTomecek** [comment]
![SO FIX IT!!!1!](https://media.giphy.com/media/GQiwhGF0oIxWg/giphy.gif)

**Comment by TomasTomecek** [comment]
Closing, feel free to reopen.
