### ISSUE TITLE
How do we name the platform configuration?

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#67]
https://strawpoll.com/k5pr2pyz

**Comment by lachmanfrantisek** [comment]
For those, who does not know, what we are thinking about:
![colin-scheme](https://user-images.githubusercontent.com/20214043/38496676-a56e31a0-3bfe-11e8-97f3-e573fffa80e0.png)

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  What will be the name of the directory, `ruleset` or `rulesets`?

**Comment by TomasTomecek** [comment]
I vote for rulesets, or colin.d (`ls -lhad /etc/*.d/)
